# ✅ EC2로 JAR 복사
- name: Deploy to EC2
  uses: appleboy/scp-action@v0.1.7
  with:
    host: ${{ secrets.EC2_HOST }}
    username: ubuntu
    key: ${{ secrets.EC2_SECRET_KEY }}
    source: "*.jar"
    target: "/home/ubuntu/app/"
    overwrite: true

# ✅ EC2에서 애플리케이션 실행
- name: Restart Spring Boot on EC2
  uses: appleboy/ssh-action@v0.1.10
  with:
    host: ${{ secrets.EC2_HOST }}
    username: ubuntu
    key: ${{ secrets.EC2_SECRET_KEY }}
    script: |
      bash /home/ubuntu/app/run-deploy.sh
